class RemoveOldColumnsSettings < ActiveRecord::Migration[5.2]
  def change
    safety_assured { remove_column :settings, :set_at_x, :integer }
    safety_assured { remove_column :settings, :set_name, :string }
    safety_assured { remove_column :settings, :set_at_y, :integer }
    safety_assured { remove_column :settings, :set_os_registration_num, :string }
    safety_assured { remove_column :settings, :set_os_registration_date, :datetime }
    safety_assured { remove_column :settings, :set_os_name, :string }
    safety_assured { remove_column :settings, :set_os_address, :string }
    safety_assured { remove_column :settings, :set_os_chief_position, :string }
    safety_assured { remove_column :settings, :set_os_chief_name, :string }
    safety_assured { remove_column :settings, :set_os_based_doc, :string }
    safety_assured { remove_column :settings, :set_org_name, :string }
    safety_assured { remove_column :settings, :set_org_address, :string }
    safety_assured { remove_column :settings, :set_org_phone, :string }
    safety_assured { remove_column :settings, :set_org_chief_position, :string }
    safety_assured { remove_column :settings, :set_org_chief_name, :string }
    safety_assured { remove_column :settings, :set_org_based_doc, :string }
    safety_assured { remove_column :settings, :set_org_chief_accountant, :string }
    safety_assured { remove_column :settings, :set_os_city, :string }

    safety_assured { remove_column :proposals, :prop_applic_address, :string }
    safety_assured { remove_column :proposals, :prop_applic_bank_detail, :text }
    safety_assured { remove_column :proposals, :prop_applic_chief, :string }
    safety_assured { remove_column :proposals, :prop_applic_code_okato, :string }
    safety_assured { remove_column :proposals, :prop_applic_code_okonh, :string }
    safety_assured { remove_column :proposals, :prop_applic_code_okp, :string }
    safety_assured { remove_column :proposals, :prop_applic_code_okpo, :string }
    safety_assured { remove_column :proposals, :prop_applic_code_okved, :string }
    safety_assured { remove_column :proposals, :prop_applic_code_tn_ved, :string }
    safety_assured { remove_column :proposals, :prop_applic_email, :string }
    safety_assured { remove_column :proposals, :prop_applic_fax, :string }
    safety_assured { remove_column :proposals, :prop_applic_from_issue, :string }
    safety_assured { remove_column :proposals, :prop_applic_inn, :string }
    safety_assured { remove_column :proposals, :prop_applic_kpp, :string }
    safety_assured { remove_column :proposals, :prop_applic_name, :string }
    safety_assured { remove_column :proposals, :prop_applic_name_product, :text }
    safety_assured { remove_column :proposals, :prop_applic_phone, :string }
    safety_assured { remove_column :proposals, :prop_applic_postcode, :string }
    safety_assured { remove_column :proposals, :prop_applic_reg_doc, :string }
    safety_assured { remove_column :proposals, :prop_applic_type_own, :string }
    safety_assured { remove_column :proposals, :prop_cert_system, :string }
    safety_assured { remove_column :proposals, :prop_date_from, :datetime }
    safety_assured { remove_column :proposals, :prop_manuf_add_info, :text }
    safety_assured { remove_column :proposals, :prop_manuf_address, :string }
    safety_assured { remove_column :proposals, :prop_manuf_chief_accountant, :string }
    safety_assured { remove_column :proposals, :prop_manuf_chief_org, :string }
    safety_assured { remove_column :proposals, :prop_manuf_code_okato, :string }
    safety_assured { remove_column :proposals, :prop_manuf_code_okonh, :string }
    safety_assured { remove_column :proposals, :prop_manuf_code_okpo, :string }
    safety_assured { remove_column :proposals, :prop_manuf_code_okved, :string }
    safety_assured { remove_column :proposals, :prop_manuf_count_sort_cert, :string }
    safety_assured { remove_column :proposals, :prop_manuf_doc, :string }
    safety_assured { remove_column :proposals, :prop_manuf_group_complexity, :string }
    safety_assured { remove_column :proposals, :prop_manuf_inn, :string }
    safety_assured { remove_column :proposals, :prop_manuf_list_doc, :text }
    safety_assured { remove_column :proposals, :prop_manuf_name, :string }
    safety_assured { remove_column :proposals, :prop_manuf_postcode, :string }
    safety_assured { remove_column :proposals, :prop_manuf_regulations, :string }
    safety_assured { remove_column :proposals, :prop_manuf_scheme_cert, :string }
    safety_assured { remove_column :proposals, :prop_manuf_type_own, :string }
    safety_assured { remove_column :proposals, :prop_number, :string }
    safety_assured { remove_column :proposals, :applic_chief, :string }
    safety_assured { remove_column :proposals, :manuf_chief_org, :string }

    safety_assured { remove_column :solution_proposals, :solprop_add_info, :string }
    safety_assured { remove_column :solution_proposals, :solprop_applic_code_okp, :string }
    safety_assured { remove_column :solution_proposals, :solprop_applic_code_tn_ved, :string }
    safety_assured { remove_column :solution_proposals, :solprop_applic_name, :string }
    safety_assured { remove_column :solution_proposals, :solprop_applic_name_product, :text }
    safety_assured { remove_column :solution_proposals, :solprop_basis_work, :string }
    safety_assured { remove_column :solution_proposals, :solprop_chief_name, :string }
    safety_assured { remove_column :solution_proposals, :solprop_chief_org, :string }
    safety_assured { remove_column :solution_proposals, :solprop_date_from, :datetime }
    safety_assured { remove_column :solution_proposals, :solprop_desc_scheme_cert, :string }
    safety_assured { remove_column :solution_proposals, :solprop_executor, :string }
    safety_assured { remove_column :solution_proposals, :solprop_expert, :string }
    safety_assured { remove_column :solution_proposals, :solprop_list_doc_product, :string }
    safety_assured { remove_column :solution_proposals, :solprop_manuf_address, :string }
    safety_assured { remove_column :solution_proposals, :solprop_manuf_doc, :string }
    safety_assured { remove_column :solution_proposals, :solprop_manuf_list_doc, :text }
    safety_assured { remove_column :solution_proposals, :solprop_manuf_name, :text }
    safety_assured { remove_column :solution_proposals, :solprop_manuf_postcode, :string }
    safety_assured { remove_column :solution_proposals, :solprop_number, :string }
    safety_assured { remove_column :solution_proposals, :solprop_regulations, :string }
    safety_assured { remove_column :solution_proposals, :solprop_sampling, :string }
    safety_assured { remove_column :solution_proposals, :solprop_solution, :string }
    safety_assured { remove_column :solution_proposals, :solprop_test_lab, :string }

    safety_assured { remove_column :certcontracts, :cecon_client_active, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_address, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_bank_details, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_based_doc, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_chief_name, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_chief_name_sign, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_chief_position, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_chief_position_sign, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_name, :string }
    safety_assured { remove_column :certcontracts, :cecon_client_named, :string }
    safety_assured { remove_column :certcontracts, :cecon_date_expiry, :datetime }
    safety_assured { remove_column :certcontracts, :cecon_date_from, :datetime }
    safety_assured { remove_column :certcontracts, :cecon_exec_active, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_address, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_bank_details, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_based_doc, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_chief_name, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_chief_name_sign, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_chief_position, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_chief_position_sign, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_name, :string }
    safety_assured { remove_column :certcontracts, :cecon_exec_named, :string }
    safety_assured { remove_column :certcontracts, :cecon_name_product, :string }
    safety_assured { remove_column :certcontracts, :cecon_price_work, :string }
    safety_assured { remove_column :certcontracts, :cecon_price_work_total, :string }
    safety_assured { remove_column :certcontracts, :cecon_registration_city, :string }
    safety_assured { remove_column :certcontracts, :cecon_registration_date, :datetime }
    safety_assured { remove_column :certcontracts, :cecon_registration_num, :string }
  end
end
